defaults:
  - 4k4d_prior_case_sparseproto_humancrop_depthnormal_coupled_r6_nopriorgeom_clean6v
  - _self_

exp_name: 4k4d_prior_case_sparseproto_humancrop_depthnormal_coupled_r15_selfgeom_headsonly

loss:
  human_prior:
    weight: 0.12
    normal: null
    point_normal: null
    depth_normal:
      consistency_weight: 0.10
      valid_range: 0.96
      orientation: unoriented
      normal_target_detach: false
      min_depth: 0.0001
      head_roi_weight: 2.0
      face_roi_weight: 3.0
      hairline_roi_weight: 3.0
      ear_band_roi_weight: 2.0
      boundary_boost: 2.0
    depth_point:
      consistency_weight: 0.10
      xyz_weight: 0.35
      z_weight: 0.7
      valid_range: 0.96
      min_depth: 0.0001
      relative_scale: true
      head_roi_weight: 2.0
      face_roi_weight: 3.0
      hairline_roi_weight: 3.0
      ear_band_roi_weight: 2.0
      boundary_boost: 2.0

optim:
  frozen_module_names:
    - aggregator
    - camera_head
