defaults:
  - zju_vggt_geom_unproject_source_policy_nearest_rawpool_confdepth_dropworst_minimal
  - _self_

exp_name: zju_vggt_geom_unproject_source_policy_nearest_rawpool_confdepth_dropworst_gradconfmask_minimal

loss:
  depth:
    respect_conf_mask_in_grad_conf: True
