defaults:
  - zju_vggt_geom_unproject_source_policy_nearest_rawpool_confdepth_dropworst_gradconfmask_minimal
  - _self_

exp_name: zju_vggt_geom_unproject_source_policy_nearest_rawpool_confdepth_dropworst_gradconfmask_anchorb1qquadraticfgedge5partialjointconfsmoothstepp60jointdepthscale0875_minimal

loss:
  depth:
    anchor_conditioned_reg_target_cameras:
      - Camera_B1
    anchor_conditioned_reg_target_scale: 0.875
    anchor_conditioned_reg_target_train_only: True
    anchor_conditioned_reg_target_quality_interp: quadratic
    anchor_conditioned_reg_target_quality_low: 2.4610
    anchor_conditioned_reg_target_quality_high: 4.4193
    anchor_conditioned_reg_target_foreground_edge_band_px: 5
    anchor_conditioned_conf_target_cameras:
      - Camera_B1
    anchor_conditioned_conf_target_scale: 0.875
    anchor_conditioned_conf_target_train_only: True
    anchor_conditioned_conf_target_quality_interp: quadratic
    anchor_conditioned_conf_target_quality_low: 2.4610
    anchor_conditioned_conf_target_quality_high: 4.4193
    anchor_conditioned_conf_target_foreground_edge_band_px: 5
    anchor_conditioned_conf_target_depth_conf_interp: smoothstep
    anchor_conditioned_conf_target_depth_conf_low: 0.0
    anchor_conditioned_conf_target_depth_conf_high: 5.913640410988592
