defaults:
  - zju_vggt_geom_unproject_source_policy_nearestplusuniformtail_rawpool_confdepth_dropworst_gradconfmask_minimal
  - _self_

exp_name: zju_vggt_geom_unproject_source_policy_nearestplusuniformtail_rawpool_confdepth_dropworst_gradconfmask_losstisolation0_minimal

loss:
  camera:
    loss_t_isolation_scale: 0.0
